# Generated by Django 2.1.7 on 2019-02-21 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Mark Per Questions')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duration of The Quiz')),
                ('total_marks', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='The Total Marksm Obtainable')),
                ('no_of_question', models.PositiveIntegerField(default=50, verbose_name='Total No of Questions')),
                ('instructions', models.TextField(default=' ')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_detailss', to='cbt.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='cbt.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_quizzes', to='cbt.Course'),
            preserve_default=False,
        ),
    ]
