# Generated by Django 2.1.7 on 2019-02-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_auto_20190223_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_choice', models.PositiveIntegerField(default=2, verbose_name='Min Number of Options')),
                ('max_choice', models.PositiveIntegerField(default=10, verbose_name='Max Number of Options')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='cbt.TakenQuiz', to='cbt.Course'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_course', to='cbt.Course'),
            preserve_default=False,
        ),
    ]
