# Generated by Django 2.1.7 on 2019-02-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_course_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ManyToManyField(related_name='department_students', to='cbt.Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='matric',
            field=models.CharField(default=1, max_length=15, verbose_name='Matric No'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'matric')},
        ),
    ]
