# Generated by Django 2.1.7 on 2019-02-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0006_auto_20190223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric',
            field=models.PositiveIntegerField(max_length=15, verbose_name='Matric No'),
        ),
    ]
