# Generated by Django 2.1.7 on 2019-02-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_user_matric'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='matric',
        ),
    ]
