# Generated by Django 2.1.7 on 2019-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_auto_20190223_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='cbt.TakenQuiz', to='cbt.Course'),
        ),
    ]
