# Generated by Django 2.1.7 on 2019-02-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0010_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Was this attempt correct?'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Marks Obtained'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='selected_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt.Answer'),
        ),
    ]
