# Generated by Django 2.1.7 on 2019-02-26 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0011_auto_20190226_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_question', to='cbt.Question'),
            preserve_default=False,
        ),
    ]
